// Generated by https://quicktype.io

export interface GetAppHome {
  message: string;
  data: Datum[];
  statusCode: number;
  status: boolean;
}

export interface Datum {
  category: Category;
  products: Product[];
}

export interface Category {
  _id: string;
  subCategories: any[];
  status: boolean;
  date: string;
  deleted: boolean;
  name: string;
  level: number;
  image: string;
  createdAt: string;
  updatedAt: string;
  slug: string;
  __v: number;
}

export interface Product {
  name: string;
  parentId: null | string;
  variants: string[];
  shortDesc: string;
  fullDesc: string;
  images: Image[];
  status: boolean;
  sizes: string[];
  rating: number;
  SKU: string;
  mrp: number;
  quantity: number;
  sellingPrice: number;
  deleted: boolean;
  _id: string;
  brand: string;
  category: string;
  subCategory: string;
  color: string;
  createdAt: string;
  updatedAt: string;
  slug: string;
  __v: number;
}

export interface Image {
  favicon?: string;
  icon?: string;
  lg?: string;
  md?: string;
  original?: string;
  sm?: string;
  x2lg?: string;
  xlg?: string;
  xs?: string;
}
