// Generated by https://quicktype.io

export interface AdsResponse {
    message:    string;
    data:       Data;
    statusCode: number;
    status:     boolean;
}

export interface Data {
    docs:  Doc[];
    count: number;
}

export interface Doc {
    location:    string;
    redirectURL: string;
    deleted:     boolean;
    _id:         string;
    file:        File;
    createdAt:   string;
    updatedAt:   string;
    __v:         number;
}

export interface File {
    xlg:      string;
    lg:       string;
    md:       string;
    sm:       string;
    xs:       string;
    original: string;
}
