// Generated by https://quicktype.io

export interface OrderDetailData {
  message:    string;
  data:       Data;
  statusCode: number;
  status:     boolean;
}

export interface Data {
  order:     Order;
  trackData: TrackDatum[];
}

export interface Order {
  _id:                string;
  paymentStatus:      string;
  date:               string;
  shippingCharge:     number;
  total:              number;
  quantity:           number;
  reviewAvailable:    boolean;
  deleted:            boolean;
  orderId:            string;
  items:              Item[];
  currentOrderStatus: string;
  orderStatus:        OrderStatus[];
  paymentMethod:      string;
  shippingAddress:    ShippingAddress;
  user:               User;
  createdAt:          string;
  updatedAt:          string;
  __v:                number;
  SROrderInfo:        SROrderInfo;
}

export interface SROrderInfo {
  order_id:                 number;
  shipment_id:              number;
  status:                   string;
  status_code:              number;
  onboarding_completed_now: number;
  awb_code:                 string;
  courier_company_id:       string;
  courier_name:             string;
}

export interface Item {
  qty:     number;
  _id:     string;
  product: Product;
  variant: VariantVariant;
}

export interface Product {
  name:            string;
  mainCategories:  any[];
  description:     string;
  images:          Image[];
  status:          boolean;
  subCategories:   any[];
  tags:            any[];
  isApproved:      string;
  date:            string;
  isFeatured:      boolean;
  metaDescription: string;
  rating:          number;
  adminRating:     number;
  reviewsCount:    number;
  viewsCount:      number;
  ratingCount:     number;
  deleted:         boolean;
  _id:             string;
  variants:        VariantElement[];
  category:        string;
  brand:           string;
  subCategory:     string;
  createdAt:       string;
  updatedAt:       string;
  slug:            string;
  __v:             number;
}

export interface Image {
  xlg:      string;
  lg:       string;
  md:       string;
  sm:       string;
  xs:       string;
  original: string;
}

export interface VariantElement {
  _id:     string;
  variant: VariantVariant;
}

export interface VariantVariant {
  _id:          string;
  quantity:     number;
  sellingPrice: number;
  mrp:          number;
  size:         string;
  color:        string;
  SKU:          string;
  deleted:      boolean;
}

export interface OrderStatus {
  _id:    string;
  status: string;
  date:   string;
  msg:    string;
}

export interface ShippingAddress {
  _id:             string;
  pickup_location: string;
  name:            string;
  email:           string;
  phone:           string;
  address:         string;
  address_2:       string;
  city:            string;
  state:           string;
  country:         string;
  pin_code:        string;
  isDefault:       boolean;
  deleted:         boolean;
  user:            string;
  createdAt:       string;
  updatedAt:       string;
  __v:             number;
}

export interface User {
  _id:  string;
  name: string;
}

export interface TrackDatum {
  tracking_data: TrackingData;
}

export interface TrackingData {
  track_status:              number;
  shipment_status:           number;
  shipment_track:            ShipmentTrack[];
  shipment_track_activities: ShipmentTrackActivity[];
  track_url:                 string;
  etd:                       string;
}

export interface ShipmentTrack {
  id:                    number;
  awb_code:              string;
  courier_company_id:    number;
  shipment_id:           number;
  order_id:              number;
  pickup_date:           null;
  delivered_date:        null;
  weight:                string;
  packages:              number;
  current_status:        string;
  delivered_to:          string;
  destination:           string;
  consignee_name:        string;
  origin:                string;
  courier_agent_details: null;
  edd:                   string;
}

export interface ShipmentTrackActivity {
  date:        string;
  status:      string;
  activity:    string;
  location:    string;
  "sr-status": string;
}
